#!/usr/bin/env python3
"""
Test script for analyzing recollapse_data.h5 files generated by
TODDLERSInterpolantGenerator.

This script:
1. Validates the HDF5 file structure
2. Analyzes recollapse statistics
3. Creates visualizations of the data
4. Checks parameter correlations
"""
import h5py
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import pytest
sns = pytest.importorskip("seaborn")  # diagnostic plots only; skip module if seaborn absent
from matplotlib.gridspec import GridSpec

# Analyses a generated recollapse_data HDF5; needs that data, so it is part of the
# 'data' set and is deselected by the default (fast) test run.
pytestmark = pytest.mark.data

def validate_hdf5_structure(h5file):
    """
    Validate the structure of the recollapse data HDF5 file.
    
    Args:
        h5file (h5py.File): Open HDF5 file
        
    Returns:
        dict: Structure validation results
    """
    results = {
        'valid': True,
        'errors': [],
        'metadata': {}
    }
    
    # Check main group exists
    if 'recollapse_data' not in h5file:
        results['valid'] = False
        results['errors'].append("Missing main 'recollapse_data' group")
        return results
        
    main_group = h5file['recollapse_data']
    
    # Check required attributes
    required_attrs = ['template', 'imf', 'star_type', 'cluster_mode', 
                     'profile_type', 'date_generated']
    for attr in required_attrs:
        if attr not in main_group.attrs:
            results['valid'] = False
            results['errors'].append(f"Missing required attribute: {attr}")
        else:
            results['metadata'][attr] = main_group.attrs[attr]
            
    # Check parameter grid group
    if 'parameter_grid' not in main_group:
        results['valid'] = False
        results['errors'].append("Missing parameter_grid group")
    else:
        param_group = main_group['parameter_grid']
        required_params = ['Z', 'eta_sf', 'n_cl', 'logM']
        for param in required_params:
            if param not in param_group:
                results['valid'] = False
                results['errors'].append(f"Missing parameter dataset: {param}")
                
    # Check simulations group
    if 'simulations' not in main_group:
        results['valid'] = False
        results['errors'].append("Missing simulations group")
        
    return results

def collect_recollapse_statistics(h5file):
    """
    Collect statistics about recollapse events.
    
    Args:
        h5file (h5py.File): Open HDF5 file
        
    Returns:
        dict: Statistics about recollapse events
    """
    print("\nCollecting Recollapse Statistics:")
    print("-" * 50)
    stats = {
        'num_simulations': 0,
        'num_with_recollapse': 0,
        'recollapse_counts': [],
        'first_recollapse_times': [],
        'time_between_recollapses': [],
        'parameters': {
            'Z': [],
            'eta_sf': [],
            'n_cl': [],
            'logM': []
        },
        'has_recollapse': []  # Track which simulations had recollapses
    }
    
    sims_group = h5file['recollapse_data/simulations']
    stats['num_simulations'] = len(sims_group)
    
    for sim_key in sims_group:
        sim = sims_group[sim_key]
        
        # Get parameters
        for param in stats['parameters']:
            stats['parameters'][param].append(sim.attrs[param])
            
        # Initialize with zero recollapses
        stats['recollapse_counts'].append(0)
        has_recollapse = False
            
        if 'recollapse_times_myr' in sim:
            times = sim['recollapse_times_myr'][:]
            if len(times) > 0:
                stats['num_with_recollapse'] += 1
                has_recollapse = True
                stats['recollapse_counts'][-1] = len(times)
                stats['first_recollapse_times'].append(times[0])
                
                # Print parameter details for simulations with recollapses
                print(f"\nRecollapse found in simulation {sim_key}:")
                print(f"  Parameters:")
                print(f"    Z = {sim.attrs['Z']:.3g}")
                print(f"    eta_sf = {sim.attrs['eta_sf']:.3g}")
                print(f"    n = {sim.attrs['n_cl']:.1f} cm⁻³")
                print(f"    log(M) = {sim.attrs['logM']:.2f}")
                print(f"  Recollapse times (Myr):")
                for i, t in enumerate(times, 1):
                    print(f"    {i}. t = {t:.2f}")
                
                if len(times) > 1:
                    time_diffs = np.diff(times)
                    print(f"  Time between recollapses (Myr):")
                    for i, dt in enumerate(time_diffs, 1):
                        print(f"    {i}. dt = {dt:.2f}")
                    stats['time_between_recollapses'].extend(time_diffs)
        
        stats['has_recollapse'].append(has_recollapse)
                
    # Convert lists to arrays
    for param in stats['parameters']:
        stats['parameters'][param] = np.array(stats['parameters'][param])
    
    stats['recollapse_counts'] = np.array(stats['recollapse_counts'])
    stats['first_recollapse_times'] = np.array(stats['first_recollapse_times'])
    stats['time_between_recollapses'] = np.array(stats['time_between_recollapses'])
    stats['has_recollapse'] = np.array(stats['has_recollapse'])
    
    return stats

def plot_recollapse_statistics(stats, output_dir):
    """
    Create visualization plots for recollapse statistics.
    
    Args:
        stats (dict): Statistics from collect_recollapse_statistics
        output_dir (Path): Directory to save plots
    """
    # Figure 1: Basic Statistics
    fig = plt.figure(figsize=(15, 10))
    gs = GridSpec(2, 2)
    
    # Plot 1: Distribution of recollapse counts
    ax1 = fig.add_subplot(gs[0, 0])
    sns.histplot(data=stats['recollapse_counts'], ax=ax1)
    ax1.set_title('Distribution of Recollapse Events per Simulation')
    ax1.set_xlabel('Number of Recollapses')
    ax1.set_ylabel('Count')
    
    # Plot 2: Distribution of first recollapse times
    ax2 = fig.add_subplot(gs[0, 1])
    sns.histplot(data=stats['first_recollapse_times'], ax=ax2)
    ax2.set_title('Distribution of First Recollapse Times')
    ax2.set_xlabel('Time (Myr)')
    ax2.set_ylabel('Count')
    
    # Plot 3: Distribution of time between recollapses
    ax3 = fig.add_subplot(gs[1, 0])
    sns.histplot(data=stats['time_between_recollapses'], ax=ax3)
    ax3.set_title('Distribution of Time Between Recollapses')
    ax3.set_xlabel('Time (Myr)')
    ax3.set_ylabel('Count')
    
    # Plot 4: Basic stats text
    ax4 = fig.add_subplot(gs[1, 1])
    ax4.axis('off')
    stats_text = (
        f"Basic Statistics:\n\n"
        f"Total Simulations: {stats['num_simulations']}\n"
        f"Simulations with Recollapse: {stats['num_with_recollapse']}\n"
        f"Recollapse Rate: {stats['num_with_recollapse']/stats['num_simulations']*100:.1f}%\n\n"
        f"Average Recollapses per Sim: {np.mean(stats['recollapse_counts']):.2f}\n"
        f"Median Recollapses per Sim: {np.median(stats['recollapse_counts']):.2f}\n"
        f"Max Recollapses in a Sim: {np.max(stats['recollapse_counts'])}\n\n"
        f"Mean Time to First Recollapse: {np.mean(stats['first_recollapse_times']):.2f} Myr\n"
        f"Median Time to First Recollapse: {np.median(stats['first_recollapse_times']):.2f} Myr\n"
        f"Mean Time Between Recollapses: {np.mean(stats['time_between_recollapses']):.2f} Myr"
    )
    ax4.text(0.05, 0.95, stats_text, va='top', fontfamily='monospace')
    
    plt.tight_layout()
    plt.savefig(output_dir / 'recollapse_basic_stats.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    # Figure 2: Parameter Correlations
    fig, axes = plt.subplots(2, 2, figsize=(15, 15))
    fig.suptitle('Parameter Correlations with First Recollapse Time', fontsize=16, y=1.02)
    
    params = list(stats['parameters'].keys())
    for i, param in enumerate(params):
        ax = axes[i//2, i%2]
        param_values = stats['parameters'][param]
        
        # Get values only for simulations that had recollapses
        mask = stats['has_recollapse']
        param_values_with_recollapse = param_values[mask]
        recollapse_times = stats['first_recollapse_times']
        
        if len(param_values_with_recollapse) > 0:
            sns.scatterplot(
                x=param_values_with_recollapse,
                y=recollapse_times,
                ax=ax
            )
            
            # Calculate correlation
            corr = np.corrcoef(param_values_with_recollapse, 
                             recollapse_times)[0,1]
            
            ax.set_title(f'{param} vs First Recollapse Time\nCorrelation: {corr:.3f}')
            ax.set_xlabel(param)
            ax.set_ylabel('Time to First Recollapse (Myr)')
            
            # Add trend line
            z = np.polyfit(param_values_with_recollapse, 
                          recollapse_times, 1)
            p = np.poly1d(z)
            ax.plot(param_values_with_recollapse, 
                   p(param_values_with_recollapse), "r--", alpha=0.8)
    
    plt.tight_layout()
    plt.savefig(output_dir / 'recollapse_parameter_correlations.png', dpi=300, bbox_inches='tight')
    plt.close()

def analyze_recollapse_data(file_path):
    """
    Main function to analyze recollapse data HDF5 file.
    
    Args:
        file_path (str|Path): Path to recollapse_data.h5 file
    """
    file_path = Path(file_path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")
        
    # Create output directory
    output_dir = file_path.parent / 'recollapse_analysis'
    output_dir.mkdir(exist_ok=True)
    
    print(f"\nAnalyzing recollapse data file: {file_path}")
    print(f"Output directory: {output_dir}")
    
    with h5py.File(file_path, 'r') as f:
        # Validate structure
        print("\nValidating HDF5 structure...")
        validation = validate_hdf5_structure(f)
        
        if not validation['valid']:
            print("HDF5 file structure validation failed:")
            for error in validation['errors']:
                print(f"  - {error}")
            return
        
        print("HDF5 file structure validated")
        print("\nMetadata:")
        for key, value in validation['metadata'].items():
            print(f"  {key}: {value}")
            
        # Collect statistics
        print("\nCollecting recollapse statistics...")
        stats = collect_recollapse_statistics(f)
        
        # Create visualizations
        print("\nGenerating visualization plots...")
        plot_recollapse_statistics(stats, output_dir)
        
    print(f"\nAnalysis complete! Results saved to: {output_dir}")

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        sys.exit("usage: python test_stab_recollapse_h5.py <recollapse_data_*.hdf5>\n"
                 "  the recollapse HDF5 written by the interpolant generator "
                 "(python -m toddlers.stab.interpolants)")
    analyze_recollapse_data(sys.argv[1])