"""Sphinx configuration for the TODDLERS public package.

The package is a single importable ``toddlers`` package (pip-installed), so the API
reference is generated by running ``sphinx-apidoc`` over ``src/toddlers`` once at build
time (see ``setup`` below). The vendored ``toddlers.pts`` subpackage (third-party, AGPL)
is excluded.
"""
import os
import sys

# Make the package importable for autodoc even without an install (e.g. local builds).
# On Read the Docs the package is pip-installed via .readthedocs.yaml, so this is a no-op there.
sys.path.insert(0, os.path.abspath("../src"))


def setup(app):
    """Generate the API .rst stubs from the package before the build."""
    import sphinx.ext.apidoc

    here = os.path.dirname(os.path.abspath(__file__))
    pkg_dir = os.path.abspath(os.path.join(here, "..", "src", "toddlers"))
    out_dir = os.path.join(here, "api")
    pts_dir = os.path.join(pkg_dir, "pts")          # vendored third-party (AGPL) -> exclude

    sphinx.ext.apidoc.main([
        "--force",          # regenerate every build
        "--module-first",   # module docstring before submodule listing
        "--separate",       # one page per module (cleaner navigation)
        "-o", out_dir,
        pkg_dir,
        pts_dir,            # exclude pattern
    ])
    return app


# -- Project information -----------------------------------------------------
project = "TODDLERS"
copyright = "2026, Anand Utsav Kapoor"
author = "Anand Utsav Kapoor"
release = "2.0"

# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",      # pull docstrings from the package
    "sphinx.ext.napoleon",     # Google- and NumPy-style docstrings (the package mixes both)
    "sphinx.ext.autosummary",  # summary tables
    "sphinx.ext.viewcode",     # links to highlighted source
    "sphinx.ext.intersphinx",  # cross-links to numpy/scipy/astropy docs
    "sphinx.ext.mathjax",      # math
    "sphinx.ext.todo",
]

templates_path = ["_templates"]
# api/modules.rst is the apidoc top-level TOC; we link api/toddlers directly, so drop it.
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "api/modules.rst"]

# Some modules pull in heavy/optional machinery; don't let a missing import break the build.
autodoc_mock_imports = []
suppress_warnings = [
    "autodoc.import_error",
    "autosummary",
    "autosummary.import_cycle",
]

autosummary_generate = True
autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    "special-members": "__init__",
    "undoc-members": True,
    "exclude-members": "__weakref__",
    "show-inheritance": True,
}

# Class docstrings list methods (Napoleon "Methods" section) and autodoc also documents
# them via :members:; silence the resulting duplicate-object-description warnings.
import sphinx.domains.python
_orig_note_object = sphinx.domains.python.PythonDomain.note_object
def _quiet_note_object(self, name, objtype, node_id, aliased=False, location=None):
    if name in self.objects:
        return
    _orig_note_object(self, name, objtype, node_id, aliased=aliased, location=location)
sphinx.domains.python.PythonDomain.note_object = _quiet_note_object

# Napoleon
napoleon_include_init_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_param = True
napoleon_use_rtype = True

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
}

# -- HTML output -------------------------------------------------------------
html_theme = "furo"
html_static_path = ["_static"]
